markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "[Catalyzing...25%]"
markdown: kramdown

author: "frankwang"
atom-baseurl: "http://weiyangthecatalyst.name"
disqus: "yipansansha"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: /gallery.html
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml